# -*- coding: utf-8 -*-
"""Email Spam Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbK5yfgT5imILDQaFQIVS8oXU1gJ5zjt
"""

import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('emails.csv')

df

df['spam'].value_counts()

df.drop_duplicates(inplace = True)

df['spam'].value_counts()

df

df.isnull().sum

"""**Separate x and y**"""

x=df.text.values

#Dependent
y=df.spam.values

"""**Split dataset**"""

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

"""**Data Preprocessing**"""

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)

x_train.toarray()

"""**ML algorithm**"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train,ytrain)

x_test = cv.transform(xtest)

x_test.toarray()

model.score(x_test,ytest)

emails =['hey i am looking for machine learning tutorial in bengali language','hey you win an iphone x giveaway for free please do the survey']

cv_emails = cv.transform(emails)

model.predict(cv_emails)